
# Loads default set of integrations. Do not remove.
default_config:

  
influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret INFLUXDB_USER
  password: !secret INFLUXDB_PASSWORD
  max_retries: 3
  default_measurement: state

sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /config
      - type: memory_free
      - type: memory_use_percent
      - type: processor_use
      - type: processor_temperature

mqtt:
  sensor:
    - name: 'TwinButtonLampBrightness'
      unique_id: 'Twin_Button_LampBrightness'
      state_topic: 'student/CASA0022/ucfnsmc/twin/LampBrightness'
    - name: 'TwinButtonStripBrightness'
      unique_id: 'Twin_Button_StripBrightness'
      state_topic: 'student/CASA0022/ucfnsmc/twin/StripBrightness'
    - name: 'TwinButtonColdLight'
      state_topic: "student/CASA0022/ucfnsmc/twin/ColdLight"
      unique_id: 'Twin_Button_ColdLight'
    - name: 'TwinButtonWarmLight'
      state_topic: "student/CASA0022/ucfnsmc/twin/WarmLight"
      unique_id: 'Twin_Button_WarmLight'
    - name: 'TwinButtonRedLight'
      state_topic: "student/CASA0022/ucfnsmc/twin/RedLight"
      unique_id: 'Twin_Button_RedLight'
    - name: 'TwinButtonStripButton'
      state_topic: "student/CASA0022/ucfnsmc/twin/StripButton"
      unique_id: 'Twin_Button_StripButton'
    - name: 'TwinButtonLampButton'
      state_topic: "student/CASA0022/ucfnsmc/twin/LampButton"
      unique_id: 'Twin_Button_LampButton'
      
    - name: 'SelfBuiltAirMonitorTemperature'
      unique_id: 'SelfBuilt_AirMonitor_Temperature'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - name: 'SelfBuiltAirMonitorPressure'
      unique_id: 'SelfBuilt_AirMonitor_Pressure'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      unit_of_measurement: 'hPa'
      value_template: '{{ value_json.pressure }}'
    - name: 'SelfBuiltAirMonitor_Humidity'
      unique_id: 'SelfBuilt_AirMonitor_Humidity'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      unit_of_measurement: '%'
      value_template: '{{ value_json.humidity }}'
    - name: 'SelfBuiltAirMonitorOxidised'
      unique_id: 'SelfBuilt_AirMonitor_Oxidised'
      unit_of_measurement: 'kO'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      value_template: '{{ value_json.oxidised }}'
    - name: 'SelfBuiltAirMonitorReduced'
      unique_id: 'SelfBuilt_AirMonitor_Reduced'
      unit_of_measurement: 'kO'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      value_template: '{{ value_json.reduced }}'
    - name: 'SelfBuiltAirMonitorNH3'
      unique_id: 'SelfBuilt_AirMonitor_nh3'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      unit_of_measurement: 'kO'
      value_template: '{{ value_json.nh3 }}'
    - name: 'SelfBuiltAirMonitorLight'
      unique_id: 'SelfBuilt_AirMonitor_Light'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      unit_of_measurement: 'lux'
      value_template: '{{ value_json.lux }}'
    - name: 'SelfBuiltAirMonitorCO2'
      unique_id: 'SelfBuilt_AirMonitor_CO2'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      unit_of_measurement: 'ppm'
      value_template: '{{ value_json.CO2 }}'
    - name: 'SelfBuiltAirMonitorVOC'
      unique_id: 'SelfBuilt_AirMonitor_VOC'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      unit_of_measurement: 'ppb'
      value_template: '{{ value_json.VOC }}'
    - name: 'SelfBuiltAirMonitorPM1'
      unique_id: 'SelfBuilt_AirMonitor_PM1'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      unit_of_measurement: 'ug/m3'
      value_template: '{{ value_json.pm1 }}'
    - name: 'SelfBuiltAirMonitorPM25'
      unique_id: 'SelfBuilt_AirMonitor_PM25'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      unit_of_measurement: 'ug/m3'
      value_template: '{{ value_json.pm25 }}'
    - name: 'SelfBuiltAirMonitorPM10'
      unique_id: 'SelfBuilt_AirMonitor_PM10'
      state_topic: 'student/CASA0022/ucfnsmc/enviroplus'
      unit_of_measurement: 'ug/m3'
      value_template: '{{ value_json.pm10 }}'
     
    - name: 'AirMonitorTemperature'
      unique_id: 'AirMonitor_Temperature'
      state_topic: 'student/CASA0022/ucfnsmc/AirMonitor'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - name: 'AirMonitorTVOC'
      unique_id: 'AirMonitor_TVOC'
      state_topic: 'student/CASA0022/ucfnsmc/AirMonitor'
      unit_of_measurement: 'ppb'
      value_template: '{{ value_json.voc }}'
    - name: 'AirMonitorHumidity'
      unique_id: 'AirMonitor_Humidity'
      state_topic: 'student/CASA0022/ucfnsmc/AirMonitor'
      unit_of_measurement: '%'
      value_template: '{{ value_json.humidity }}'
    - name: 'AirMonitorBattery'
      unique_id: 'AirMonitor_Battery'
      state_topic: 'student/CASA0022/ucfnsmc/AirMonitor'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'
    - name: 'AirMonitorLinkQuality'
      unique_id: 'AirMonitor_LinkQuality'
      state_topic: 'student/CASA0022/ucfnsmc/AirMonitor'
      value_template: '{{ value_json.linkquality }}'
    - name: 'AirMonitorVoltage'
      unique_id: 'AirMonitor_Voltage'
      state_topic: 'student/CASA0022/ucfnsmc/AirMonitor'
      unit_of_measurement: 'V'
      value_template: '{{ value_json.voltage }}'
    - name: 'Motion1_Battery'
      unique_id: 'Motion1_Battery'
      state_topic: 'student/CASA0022/ucfnsmc/Motion1'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'
    - name: 'Motion1_Linkquality'
      unique_id: 'Motion1_Linkquality'
      state_topic: 'student/CASA0022/ucfnsmc/Motion1'
      value_template: '{{ value_json.linkquality }}'
    - name: 'Motion1_Temperature'
      unique_id: 'Motion1_Temperature'
      state_topic: 'student/CASA0022/ucfnsmc/Motion1'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - name: 'Motion1_Voltage'
      unique_id: 'Motion1_Voltage'
      state_topic: 'student/CASA0022/ucfnsmc/Motion1'
      unit_of_measurement: 'V'
      value_template: '{{ value_json.voltage }}'
    - name: 'Motion1_Illuminance'
      unique_id: 'Motion1_Illuminance'
      state_topic: 'student/CASA0022/ucfnsmc/Motion1'
      unit_of_measurement: 'lx'
      value_template: '{{ value_json.illuminance }}'
    - name: 'Motion2_Battery'
      unique_id: 'Motion2_Battery'
      state_topic: 'student/CASA0022/ucfnsmc/Motion2'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'
    - name: 'Motion2_Linkquality'
      unique_id: 'Motion2_Linkquality'
      state_topic: 'student/CASA0022/ucfnsmc/Motion2'
      value_template: '{{ value_json.linkquality }}'
    - name: 'Motion2_Temperature'
      unique_id: 'Motion2_Temperature'
      state_topic: 'student/CASA0022/ucfnsmc/Motion2'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - name: 'Motion2_Voltage'
      unique_id: 'Motion2_Voltage'
      state_topic: 'student/CASA0022/ucfnsmc/Motion2'
      unit_of_measurement: 'V'
      value_template: '{{ value_json.voltage }}'
    - name: 'Motion2_Illuminance'
      unique_id: 'Motion2_Illuminance'
      state_topic: 'student/CASA0022/ucfnsmc/Motion2'
      unit_of_measurement: 'lx'
      value_template: '{{ value_json.illuminance }}'
    - name: 'Motion3_Battery'
      unique_id: 'Motion3_Battery'
      state_topic: 'student/CASA0022/ucfnsmc/Motion3'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'
    - name: 'Motion3_Linkquality'
      unique_id: 'Motion3_Linkquality'
      state_topic: 'student/CASA0022/ucfnsmc/Motion3'
      value_template: '{{ value_json.linkquality }}'
    - name: 'Motion3_Temperature'
      unique_id: 'Motion3_Temperature'
      state_topic: 'student/CASA0022/ucfnsmc/Motion3'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - name: 'Motion3_Voltage'
      unique_id: 'Motion3_Voltage'
      state_topic: 'student/CASA0022/ucfnsmc/Motion3'
      unit_of_measurement: 'V'
      value_template: '{{ value_json.voltage }}'
    - name: 'Motion3_Illuminance'
      unique_id: 'Motion3_Illuminance'
      state_topic: 'student/CASA0022/ucfnsmc/Motion3'
      unit_of_measurement: 'lx'
      value_template: '{{ value_json.illuminance }}'
    - name: 'Door1_Battery'
      unique_id: 'Door1_Battery'
      state_topic: 'student/CASA0022/ucfnsmc/Door1'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'
    - name: 'Door1_Linkquality'
      unique_id: 'Door1_Linkquality'
      state_topic: 'student/CASA0022/ucfnsmc/Door1'
      value_template: '{{ value_json.linkquality }}'
    - name: 'Door1_Temperature'
      unique_id: 'Door1_Temperature'
      state_topic: 'student/CASA0022/ucfnsmc/Door1'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - name: 'Door1_Voltage'
      unique_id: 'Door1_Voltage'
      state_topic: 'student/CASA0022/ucfnsmc/Door1'
      unit_of_measurement: 'V'
      value_template: '{{ value_json.voltage }}'
    - name: 'Door2_Battery'
      unique_id: 'Door2_Battery'
      state_topic: 'student/CASA0022/ucfnsmc/Door2'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'
    - name: 'Door2_Linkquality'
      unique_id: 'Door2_Linkquality'
      state_topic: 'student/CASA0022/ucfnsmc/Door2'
      value_template: '{{ value_json.linkquality }}'
    - name: 'Door2_Temperature'
      unique_id: 'Door2_Temperature'
      state_topic: 'student/CASA0022/ucfnsmc/Door2'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - name: 'Door2_Voltage'
      unique_id: 'Door2_Voltage'
      state_topic: 'student/CASA0022/ucfnsmc/Door2'
      unit_of_measurement: 'V'
      value_template: '{{ value_json.voltage }}'
    - name: 'Door3_Battery'
      unique_id: 'Door3_Battery'
      state_topic: 'student/CASA0022/ucfnsmc/Door3'
      unit_of_measurement: '%'
      value_template: '{{ value_json.battery }}'
    - name: 'Door3_Linkquality'
      unique_id: 'Door3_Linkquality'
      state_topic: 'student/CASA0022/ucfnsmc/Door3'
      value_template: '{{ value_json.linkquality }}'
    - name: 'Door3_Temperature'
      unique_id: 'Door3_Temperature'
      state_topic: 'student/CASA0022/ucfnsmc/Door3'
      unit_of_measurement: '°C'
      value_template: '{{ value_json.temperature }}'
    - name: 'Door3_Voltage'
      unique_id: 'Door3_Voltage'
      state_topic: 'student/CASA0022/ucfnsmc/Door3'
      unit_of_measurement: 'V'
      value_template: '{{ value_json.voltage }}'
  binary_sensor:
    - name: 'Motion1_Occupancy'
      unique_id: 'Motion1_Occupancy'
      state_topic: 'student/CASA0022/ucfnsmc/Motion1'
      value_template: '{{ iif(value_json.occupancy == true, "ON", "OFF")  }}'
    - name: 'Motion2_Occupancy'
      unique_id: 'Motion2_Occupancy'
      state_topic: 'student/CASA0022/ucfnsmc/Motion2'
      value_template: '{{ iif(value_json.occupancy == true, "ON", "OFF") }}'
    - name: 'Motion3_Occupancy'
      unique_id: 'Motion3_Occupancy'
      state_topic: 'student/CASA0022/ucfnsmc/Motion3'
      value_template: '{{ iif(value_json.occupancy == true, "ON", "OFF") }}'
    - name: 'Door1_Contact'
      unique_id: 'Door1_Contact'
      state_topic: 'student/CASA0022/ucfnsmc/Door1'
      value_template: '{{ iif(value_json.contact == true, "ON", "OFF")  }}'
    - name: 'BathroomDoor_Contact'
      unique_id: 'Door2_Contact'
      state_topic: 'student/CASA0022/ucfnsmc/Door2'
      value_template: '{{ iif(value_json.contact == true, "ON", "OFF")  }}'
    - name: 'Window_Contact'
      unique_id: 'Door3_Contact'
      state_topic: 'student/CASA0022/ucfnsmc/Door3'
      value_template: '{{ iif(value_json.contact == true, "ON", "OFF")  }}'

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
